### ISSUE TITLE
网页运行显示500错误

### ISSUE THREAD

**Issue by li-fengming** [DEIT-2020/questions_answers#23]
可以连接到数据库并对数据库中的表格进行修改，运行下列编码时页面可以正常显示：
```
`@Operation.get('id')
  Future<Response> getid() async {

    return Response.ok("getid");
  }`
```
但是运行下列代码
```
`@Operation.get()
  Future<Response> getAllSdofixes() async {
 final query = Query<Selfdofix>(context);
      final List<Selfdofix> selfdofixes=await query.fetch();
      return Response.ok(selfdofixes);}
}`
```
就出现下列错误代码，页面出现500错误：

```
`[SEVERE] aqueduct: GET /heroes 16ms 500 {user-agent : Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36\nconnection : keep-alive\ncache-control : max-age=0\naccept :text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\naccept-language : zh-CN,zh;q=0.9\nsec-fetch-mode : navigate\naccept-encoding : gzip, deflate, br\nsec-fetch-user : ?1\nhost : 127.0.0.1:8888\nsec-fetch-site : cross-site\nupgrade-insecure-requests : 1\n}  NoSuchMethodError: The getter 'dataModel' was called on null.
或下面的错误aqueduct: GET /heroes 0ms 500 {user-agent : Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36\nconnection : keep-alive\ncache-control : max-age=0\naccept : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\naccept-language : zh-CN,zh;q=0.9\nsec-fetch-mode : navigate\naccept-encoding : gzip, deflate, br\nsec-fetch-user : ?1\nhost : 127.0.0.1:8888\nsec-fetch-site : cross-site\nupgrade-insecure-requests : 1\n}  NoSuchMethodError: The getter 'dataModel' was called on null.
Receiver: null
Tried calling: dataModel #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)   
#1      new Query (package:aqueduct/src/db/query/query.dart:30:28)
#2      HeroesController.getAllHeroes (package:heroes/controller/heroes_controller.dart:12:21)  
<asynchronous suspension>
#3      _LocalInstanceMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:327:37)
#4      _LocalInstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:323:25)
#5      BoundOperation.invoke (package:aqueduct/src/http/resource_controller_internal/controller.dart:24:10)
#6      ResourceController._process (package:aqueduct/src/http/resource_controller.dart:371:36) 
<asynchronous suspension>
#7      ResourceController.handle (package:aqueduct/src/http/resource_controller.dart:138:14)   
<asynchronous suspension>
#8      Controller.receive (package:aqueduct/src/http/controller.dart:174:30)
<asynchronous suspension>
#9      _ControllerRecycler.receive (package:aqueduct/src/http/controller.dart:402:17)
#10     Controller.receive (package:aqueduct/src/http/controller.dart:206:28)
<asynchronous suspension>
#11     Router.receive (package:aqueduct/src/http/router.dart:139:18)
<asynchronous suspension>
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#16     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#21     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#22     _StreamController._add (dart:async/stream_controller.dart:640:7)
#23     _StreamController.add (dart:async/stream_controller.dart:586:5)
#24     _HttpServer._handleRequest (dart:_http/http_impl.dart:2670:19)
#25     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2428:19)
#26     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#30     _StreamController._add (dart:async/stream_controller.dart:640:7)
#31     _StreamController.add (dart:async/stream_controller.dart:586:5)
#32     _HttpParser._headersEnd (dart:_http/http_parser.dart:372:19)
#33     _HttpParser._doParse (dart:_http/http_parser.dart:701:15)
#34     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#35     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#36     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#39     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#40     _StreamController._add (dart:async/stream_controller.dart:640:7)
#41     _StreamController.add (dart:async/stream_controller.dart:586:5)
#42     _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#43     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#46     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#47     _StreamController._add (dart:async/stream_controller.dart:640:7)
#48     _StreamController.add (dart:async/stream_controller.dart:586:5)
#49     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1335:33)
#50     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:856:14)
#51     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#52     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#53     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)`
```

**Comment by li-fengming** [comment]
channel.dart代码：

`import` 'package:heroes/model/hero.dart';

import 'package:heroes/model/self-dofix.dart';
import 'heroes.dart';
import 'controller/heroes_controller.dart';
import 'controller/l-self-dofixes_controller.dart';
import 'controller/h-search-dofix_controller.dart';
import 'controller/w-wordcard_controller.dart';

import 'controller/usercontroller.dart';

/// This type initializes an application.
///
/// Override methods in this class to set up routes and initialize services like
/// database connections. See http://aqueduct.io/docs/http/channel/.
class HeroesChannel extends ApplicationChannel {
  ManagedContext context;

  //ManagedContext context;

  /// Initialize services in this method.
  ///
  /// Implement this method to initialize services, read values from [options]
  /// and any other initialization required before constructing [entryPoint].
  ///
  /// This method is invoked prior to [entryPoint] being accessed.
  @override
  Future prepare() async {
    logger.onRecord.listen((rec) => print("$rec ${rec.error ?? ""} ${rec.stackTrace ?? ""}"));
  final config = HeroConfig(options.configurationFilePath);
    
    final dataModel = ManagedDataModel.fromCurrentMirrorSystem();
      //final persistentStore = PostgreSQLPersistentStore.fromConnectionInfo(
      //"iflyup", "729at3663", "13.115.53.84", 5432, "difix");
       final persistentStore = PostgreSQLPersistentStore.fromConnectionInfo(
        config.database.username,
        config.database.password,
        config.database.host,
        config.database.port,
        config.database.databaseName);

    context = ManagedContext(dataModel, persistentStore);
  }

  /// Construct the request channel.
  ///
  /// Return an instance of some [Controller] that will be the initial receiver
  /// of all [Request]s.
  ///
  /// This method is invoked after [prepare].
  @override
  Controller get entryPoint {
     final router = Router();

        ManagedContext context;
        
         //词缀库//定义路由、请求链接等，在启动期间调用

         router
         .route('/heroes')
         .link(() => HeroesController(context));

    //login
      router
        .route("/login")
        .link(() => UserController(context));
    
    //searchfixes查询词缀库
      router
         .route('/dofixes')//查询词缀
         .link(() => SearchdofixController(context));
      router
         .route('/dofixes/:id')//显示词缀的常用意思
         .link(() => SearchdofixController(context));
      router
         .route('/word-dofixes')//查询单词
         .link(() => SearchwordsController(context));
      router
         .route('/word-dofixes/:id')//显示单词包含的词缀
         .link(() => SearchwordsController(context)); 

  
           //wordcards
      router
         .route("/wordcards")//根据词缀显示记忆卡片
         .link(() => WordcardsController(context));
      router
         .route("/wordcards_times/:id")//根据词缀显示记忆卡片记忆次数
         .link(() =>  WordcardsController(context));
      router
         .route("/wordcards_game")//根据词缀选中文，根据词缀加中文选单词
         .link(() =>  WordcardsController(context));
  

      //selfdofixes自建词缀库，充实每个词缀的单词库
      router
         .route('/selfdofixes')//词缀库显示所有已经添加的词缀
         .link(() => SelfdofixesController(context));
      router
         .route('/self-dofixes/:id')//词缀库详细显示每个词缀中对应的单词
         .link(() => SelfdofixController(context));
      router
         .route('self-dofixes/unknown')//词缀库显示未分析出的单词
         .link(() => UnknowController(context));
      router
         .route('/self-dofixes/print')//显示词缀表格
         .link(() => PrintController(context));
    

    // Prefer to use `link` instead of `linkFunction`.
    // See: https://aqueduct.io/docs/http/request_controller/
    /*router
      .route("/example")
      .linkFunction((request) async {
        return Response.ok({"key": "value"});
      });*/

    return router;
    }
    
  
  
}
class HeroConfig extends Configuration {
  HeroConfig(String path) : super.fromFile(File(path));

  DatabaseConfiguration database;
}`
ManagedObject代码：
`abstract class ManagedObject<T> extends Serializable {
  /// Creates a new instance of [entity] with [backing].
  static ManagedObject instantiateDynamic(ManagedEntity entity,
      {ManagedBacking backing}) {
    ManagedObject object = entity.instanceType
        .newInstance(const Symbol(""), []).reflectee as ManagedObject;
    if (backing != null) {
      object.backing = backing;
    }

    object.entity = entity;
    
    return object;
  }

  static bool get shouldAutomaticallyDocument => false;

  /// The [ManagedEntity] this instance is described by.
  ManagedEntity entity = ManagedDataModelManager.findEntity(T);`

**Comment by meflyup** [comment]
解决了没有？
